name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tiny-installer-debug-build:
    name: Build Tiny Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      
      - name: Build with Gradle
        id: gradle_build_debug
        run: ./gradlew assembleDebug

      - name: Upload preview debug apk
        uses: actions/upload-artifact@v4
        with:
          name: tiny-installer-preview-debug
          compression-level: 0
          path: app/build/outputs/apk/preview/debug
          
      - name: Upload stable debug apk
        uses: actions/upload-artifact@v4
        with:
          name: tiny-installer-stable-debug
          compression-level: 0
          path: app/build/outputs/apk/stable/debug
          
      - name: Upload unstable debug apk
        uses: actions/upload-artifact@v4
        with:
          name: tiny-installer-unstable-debug
          compression-level: 0
          path: app/build/outputs/apk/unstable/debug
          
  tiny-installer-release-build:
    name: Build Tiny Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      
      - name: Build with Gradle
        id: gradle_build_release
        run: ./gradlew assembleRelease

      - name: Upload preview release apk
        uses: actions/upload-artifact@v4
        with:
          name: tiny-installer-preview-release
          compression-level: 0
          path: app/build/outputs/apk/preview/release
          
      - name: Upload stable release apk
        uses: actions/upload-artifact@v4
        with:
          name: tiny-installer-stable-release
          compression-level: 0
          path: app/build/outputs/apk/stable/release 
          
      - name: Upload unstable release apk
        uses: actions/upload-artifact@v4
        with:
          name: tiny-installer-unstable-release
          compression-level: 0
          path: app/build/outputs/apk/unstable/release
          
  send_release_preview_apk:
    name: Send Preview Release APK
    runs-on: ubuntu-latest
    needs: tiny-installer-release-build
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Download preview release apk
        uses: actions/download-artifact@v4
        with:
          name: tiny-installer-preview-release
          
      - name: Get the last commit message
        id: get_commit_msg
        run: |
          commit_message=$(git log -1 --pretty=format:'%s')
          echo "message=$commit_message" >> $GITHUB_OUTPUT
          
      - name: Rename file 
        run: |
          mv app-preview-release tiny-installer-preview.apk
          ls 

      - name: Send APK Preview Release Channel Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          document: tiny-installer-preview.apk
          disable_web_page_preview: false
          message: |
            *${{ github.actor }}* committed to [${{ github.repository }}](https://github.com/${{ github.repository }})

            Branch: *${{ github.head_ref }}*
            Commit message: `${{ steps.get_commit_msg.outputs.message }}`
  
  send_release_stable_apk:
    name: Send Stable Release APK
    runs-on: ubuntu-latest
    needs: tiny-installer-release-build
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Download stable release apk
        uses: actions/download-artifact@v4
        with:
          name: tiny-installer-stable-release
          
      - name: Get the last commit message
        id: get_commit_msg
        run: |
          commit_message=$(git log -1 --pretty=format:'%s')
          echo "message=$commit_message" >> $GITHUB_OUTPUT
          
      - name: Rename file 
        run: |
          mv app-stable-release.apk tiny-installer-stable-.apk
          ls 

      - name: Send APK Stable Release Channel Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          document: tiny-installer-stable.apk
          disable_web_page_preview: false
          message: |
            *${{ github.actor }}* committed to [${{ github.repository }}](https://github.com/${{ github.repository }})

            Branch: *${{ github.head_ref }}*
            Commit message: `${{ steps.get_commit_msg.outputs.message }}`
  
  send_release_unstable_apk:
    name: Send Unstable Release APK
    runs-on: ubuntu-latest
    needs: tiny-installer-release-build
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Download unstable release apk
        uses: actions/download-artifact@v4
        with:
          name: tiny-installer-unstable-release
          
      - name: Get the last commit message
        id: get_commit_msg
        run: |
          commit_message=$(git log -1 --pretty=format:'%s')
          echo "message=$commit_message" >> $GITHUB_OUTPUT
          
      - name: Rename file 
        run: |
          mv app-unstable-release.apk tiny-installer-unstable-.apk
          ls 

      - name: Send APK Unstable Release Channel Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          document: tiny-installer-unstable.apk
          disable_web_page_preview: false
          message: |
            *${{ github.actor }}* committed to [${{ github.repository }}](https://github.com/${{ github.repository }})

            Branch: *${{ github.head_ref }}*
            Commit message: `${{ steps.get_commit_msg.outputs.message }}`